name: Second Workflow

on: workflow_dispatch

jobs:
  hello_word_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: hkeel/github-actions-studying@v1
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-numer "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-numer }}
